Ci add tests on react components/ add types
tsedio/tsed-formio pull request #68
Opened 2022-05-02 16:17 UTC by sofianeSghiouar

Romain should i use import { ComponentStory, ComponentMeta } from '@storybook/react';
like that :

2022-05-04 09:56 UTC, Romakita requested changes

2022-05-04 09:56 UTC, Romakita commented on packages/react-formio/src/components/pagination/pagination.component.spec.tsx
> +describe("Pagination", () => {
en fait, pour couvrir le composant, il faudrait que tu vérifies aussi les actions possibles.

Par exemple, quand tu cliques sur un bouton dans le composant tu dois t'attendre a être rappelé avec le changement d'état.

Si tu regardes le lien suivant, tu as une propriété qui va etre rappelé au clic d'un des éléments de la pagination:
https://github.com/tsedio/tsed-formio/blob/master/packages/react-formio/src/components/pagination/pagination.component.tsx#L67

Pour çà tu peux déclencher avec react testing library un clic et ensuite observer le résultat!

2022-05-04 17:27 UTC, sofianeSghiouar commented on packages/react-formio/src/components/pagination/pagination.component.spec.tsx
> +      Array.prototype.some.call(wrappersBtn, (wrap) =>
I'm not sure for this test, maybe in some case buttons "previous" and "next" have not class name "disabled"

2022-05-04 17:28 UTC, sofianeSghiouar commented on packages/react-formio/src/components/pagination/pagination.component.tsx
> +      active={active}
I'm not sure for the line 33 and 37

2022-05-04 17:32 UTC, sofianeSghiouar commented on packages/react-formio/src/components/pagination/pagination.component.spec.tsx
> +    expect(
maybe test from line 59 to 78 are useless

2022-05-07 07:19 UTC, Romakita approved these changes

2022-05-09 08:17 UTC, merged

2022-05-09 08:27 UTC, Romakita commented
:tada: This PR is included in version 1.11.2 :tada:

The release is available on:
- `v1.11.2`
- [GitHub release](https://github.com/tsedio/tsed-formio/releases/tag/v1.11.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: