ci: form-control, stories and tests added
tsedio/tsed-formio pull request #77
Opened 2022-05-17 15:42 UTC by sofianeSghiouar

2022-05-18 16:26 UTC, Romakita requested changes

2022-05-18 16:26 UTC, Romakita commented on packages/react-formio/src/components/form-control/formControl.component.spec.tsx
> +  it("should display suffix ", () => {
"should display suffix " => "should display suffix"

2022-05-18 16:26 UTC, Romakita commented on packages/react-formio/src/components/form-control/formControl.component.spec.tsx
> +    expect(formControlSuffix).toBeInTheDocument();
Du coup tu ne vérifies pas que ton suffix soit bien affiché dans le block suffixe. C'est un peu l'objet de ton test :)

2022-05-18 16:26 UTC, Romakita commented on packages/react-formio/src/components/form-control/formControl.component.spec.tsx
> +    expect(formControlDescription).toBeInTheDocument();
idem, là on ne voit pas ton test qui chercher à vérifier que la description est bien dans le block

2022-05-27 09:06 UTC, Romakita requested changes

2022-05-27 09:06 UTC, Romakita commented on packages/react-formio/src/components/form-control/formControl.component.spec.tsx
> +  it("should display suffix ", () => {
toujours l'espace en trop :)

2022-05-27 09:06 UTC, Romakita commented on packages/react-formio/src/components/tabs/tabs.component.tsx
> +      <button data-testid="button-tab"
on devrait pas avoir modification dans ce fichier pour cette PR :)

2022-05-27 11:41 UTC, sofianeSghiouar commented on packages/react-formio/src/components/tabs/tabs.component.tsx
> +      <button data-testid="button-tab"
^^'

2022-07-08 19:38 UTC, closed without merging